apiVersion: v2
name: demo-chart-01
appVersion: "1.0"
description: A Demo Helm chart for Connected Applications
version: 1.0.0
type: application
dependencies: 
- name: traefik
  version: 32.1.1
  repository: https://traefik.github.io/charts
